name: Sync Non-dot Directories to fuwari

on:
  push:
    branches:
      - main  # 监听 CAMELLIAKnowledgeBase 的 main 分支

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout 源仓库代码
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 拉取完整历史

      # 2. Clone 目标仓库
      - name: Clone target repo
        env:
          TARGET_REPO_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
        run: |
          git clone https://x-access-token:${TARGET_REPO_TOKEN}@github.com/camelliaxiaohua/fuwari.git target-repo
          cd target-repo
          git checkout main
          cd ..

      # 3. 同步非隐藏文件/目录到目标目录
      - name: Copy non-dot directories safely
        run: |
          TARGET_DIR="target-repo/src/content/posts"
          mkdir -p $TARGET_DIR

          # 先清空目标目录，但保留 .gitkeep 文件
          find $TARGET_DIR -mindepth 1 ! -name ".gitkeep" -exec rm -rf {} +

          # 遍历源仓库根目录的非隐藏文件/目录
          for item in *; do
            # 排除隐藏文件/目录和目标仓库目录
            if [[ "$item" != .* ]] && [[ "$item" != "target-repo" ]]; then
              cp -r "$item" "$TARGET_DIR/"
            fi
          done

      # 4. Commit & Push 更新到目标仓库
      - name: Commit and push
        env:
          TARGET_REPO_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
        run: |
          cd target-repo
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add src/content/posts/*
          
          # 如果没有变化，跳过 commit
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Sync non-dot directories from CAMELLIAKnowledgeBase"
            git push origin main
          fi
